CREATE TYPE food_category_type AS ENUM ENUM('Fruits','MEATS','VEGETABLES','GRAINS','DAIRY','DRINKS','OTHERS')
CREATE TABLE tb_foods(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    category food_category_type NOT NULL,
    quantity INT,
    "Validity" DATE,
    calories INT
);